/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompActivation: typeof import('./src/components/CompActivation.vue')['default']
    CompDateTime: typeof import('./src/components/CompDateTime.vue')['default']
    CompFooter: typeof import('./src/components/CompFooter.vue')['default']
    CompHeroSearch: typeof import('./src/components/CompHeroSearch.vue')['default']
    CompNavigation: typeof import('./src/components/CompNavigation.vue')['default']
    copy: typeof import('./src/components/SearchResult copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
    'SearchResult copy': typeof import('./src/components/SearchResult copy.vue')['default']
  }
}
