/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompActivation: typeof import('./src/components/CompActivation.vue')['default']
    CompAppBar: typeof import('./src/components/CompAppBar.vue')['default']
    CompBan2x2Basic: typeof import('./src/components/CompBan2x2Basic.vue')['default']
    CompBuildingDetail: typeof import('./src/components/CompBuildingDetail.vue')['default']
    CompBuildingImage: typeof import('./src/components/CompBuildingImage.vue')['default']
    CompBuildingMap: typeof import('./src/components/CompBuildingMap.vue')['default']
    CompBuildingView: typeof import('./src/components/CompBuildingView.vue')['default']
    CompFooter: typeof import('./src/components/CompFooter.vue')['default']
    CompNavBar: typeof import('./src/components/CompNavBar.vue')['default']
    CompNavItemHeading: typeof import('./src/components/CompNavItemHeading.vue')['default']
    CompStatBox: typeof import('./src/components/CompStatBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PaneTenantListView: typeof import('./src/components/PaneTenantListView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
